version: '3.9'

services:

  postgres:
    image: postgres:alpine
    container_name: hiber
    restart: always
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: apptest
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123

      spring:
      jpa:
      hibernate: ddl-auto=create
